name: Cypress Tests

on: push

jobs: 
  cypress-tests:
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [12.x, 14.x, 16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: cypress run
        uses: cypress-io/github-action@v2
        with: 
          build: npm run build
          start: npm start
