import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Colin Gardiner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Colin Gardiner
        </h1>
        <h2>
          Software Engineer
        </h2>

        <p className={styles.description}>
          Experience in developing web applications with JavaScript, NodeJS and React
        </p>
        <div>
        <Image 
          src="/images/selfie.png" 
          alt="profile picture"
          width={480}
          height={480}
          layout="intrinsic"
        />
        </div>
      </main>
    </div>
    </Layout>
  )
}
