import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/layout'

function MyApp({ Component, pageProps }) {
  return (
  <Layout>
    <Head>
        <title>Colin Gardiner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </Head>
    <Component {...pageProps} />
  </Layout>
  )
}

export default MyApp
